name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - v3-develop
jobs:
  ci:
    name: ci
    uses: plcdnl/.github/.github/workflows/deploy-docs-and-changelog.yml@main
    with:
      plugin_handle: videos
    secrets: inherit
